// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: audio.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Audio_Synthesizer_FullMethodName = "/audio.Audio/Synthesizer"
)

// AudioClient is the client API for Audio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type AudioClient interface {
	// 定义 RPC 方法
	Synthesizer(ctx context.Context, in *SynthesizerRequest, opts ...grpc.CallOption) (*SynthesizerReply, error)
}

type audioClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioClient(cc grpc.ClientConnInterface) AudioClient {
	return &audioClient{cc}
}

func (c *audioClient) Synthesizer(ctx context.Context, in *SynthesizerRequest, opts ...grpc.CallOption) (*SynthesizerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizerReply)
	err := c.cc.Invoke(ctx, Audio_Synthesizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioServer is the server API for Audio service.
// All implementations must embed UnimplementedAudioServer
// for forward compatibility.
//
// 定义服务
type AudioServer interface {
	// 定义 RPC 方法
	Synthesizer(context.Context, *SynthesizerRequest) (*SynthesizerReply, error)
	mustEmbedUnimplementedAudioServer()
}

// UnimplementedAudioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioServer struct{}

func (UnimplementedAudioServer) Synthesizer(context.Context, *SynthesizerRequest) (*SynthesizerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Synthesizer not implemented")
}
func (UnimplementedAudioServer) mustEmbedUnimplementedAudioServer() {}
func (UnimplementedAudioServer) testEmbeddedByValue()               {}

// UnsafeAudioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServer will
// result in compilation errors.
type UnsafeAudioServer interface {
	mustEmbedUnimplementedAudioServer()
}

func RegisterAudioServer(s grpc.ServiceRegistrar, srv AudioServer) {
	// If the following call pancis, it indicates UnimplementedAudioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Audio_ServiceDesc, srv)
}

func _Audio_Synthesizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServer).Synthesizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audio_Synthesizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServer).Synthesizer(ctx, req.(*SynthesizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Audio_ServiceDesc is the grpc.ServiceDesc for Audio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Audio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.Audio",
	HandlerType: (*AudioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Synthesizer",
			Handler:    _Audio_Synthesizer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio.proto",
}
