# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_pb2 as audio__pb2


class AudioStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesizer = channel.unary_unary(
                '/audio.Audio/Synthesizer',
                request_serializer=audio__pb2.SynthesizerRequest.SerializeToString,
                response_deserializer=audio__pb2.SynthesizerReply.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/audio.Audio/Transcribe',
                request_serializer=audio__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=audio__pb2.TranscribeReply.FromString,
                _registered_method=True)


class AudioServicer(object):
    """定义服务
    """

    def Synthesizer(self, request, context):
        """定义 RPC 方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesizer': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesizer,
                    request_deserializer=audio__pb2.SynthesizerRequest.FromString,
                    response_serializer=audio__pb2.SynthesizerReply.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=audio__pb2.TranscribeRequest.FromString,
                    response_serializer=audio__pb2.TranscribeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio.Audio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audio.Audio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Audio(object):
    """定义服务
    """

    @staticmethod
    def Synthesizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.Audio/Synthesizer',
            audio__pb2.SynthesizerRequest.SerializeToString,
            audio__pb2.SynthesizerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.Audio/Transcribe',
            audio__pb2.TranscribeRequest.SerializeToString,
            audio__pb2.TranscribeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
