# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2I\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x42|\n\x0e\x63om.helloworldB\x0fHelloworldProtoP\x01Z\x11\x61pp/protos;protos\xa2\x02\x03HXX\xaa\x02\nHelloworld\xca\x02\nHelloworld\xe2\x02\x16Helloworld\\GPBMetadata\xea\x02\nHelloworldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.helloworldB\017HelloworldProtoP\001Z\021app/protos;protos\242\002\003HXX\252\002\nHelloworld\312\002\nHelloworld\342\002\026Helloworld\\GPBMetadata\352\002\nHelloworld'
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=66
  _globals['_HELLOREPLY']._serialized_start=68
  _globals['_HELLOREPLY']._serialized_end=106
  _globals['_GREETER']._serialized_start=108
  _globals['_GREETER']._serialized_end=181
# @@protoc_insertion_point(module_scope)
